name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Set up Go
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: 1.16

    - name: Vet
      working-directory: claat
      run: go vet ./...

    - name: Build
      working-directory: claat
      run: go build -v ./...

    - name: Test
      working-directory: claat
      run: go test -v ./...
